spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
